### ISSUE TITLE
Implement Twitter Engagement Tracking Durable Object

### ISSUE THREAD

**Issue by r0zar** [aibtcdev/aibtcdev-cache#17]
# Implement Twitter Engagement Tracking Durable Object

## Overview
Create a Cloudflare Durable Object to track Twitter/X post engagement metrics with rate-limited API calls and caching.

### Types
```typescript
type Tweet = {
  id: string;
  text: string;
  created_at: string;
  metrics: TweetMetrics;
};

type TweetMetrics = {
  repost_count: number;
  reply_count: number;
  like_count: number;
  quote_count: number;
  impression_count: number;
  bookmark_count: number;
};
```

### Durable Object Configuration
- Base API URL: `https://api.twitter.com/2`
- Rate limit: 75 requests per 15 minutes
- Cache TTL: 15 minutes
- Supported endpoints:
  - `/2/users/:id/tweets` (with metrics expansion)
  - `/2/users/reposts_of_me`

### Core Features
1. Rate-limited Twitter API fetching
   - [ ] Implement rate limiting at 75 requests/15min
   - [ ] Handle API response errors and retries
   - [ ] Track rate limit headers from Twitter API

2. Data Caching
   - [ ] Cache tweet engagement metrics in KV store
   - [ ] Implement cache invalidation strategy
   - [ ] Handle cache misses gracefully

3. Periodic Updates
   - [ ] Set up alarm handler for regular updates
   - [ ] Implement backoff strategy for failed updates
   - [ ] Log update performance metrics

4. API Endpoints
   - [ ] GET `/tweets/recent` - Get recent tweets with metrics
   - [ ] GET `/tweets/:id/metrics` - Get metrics for specific tweet
   - [ ] GET `/tweets/reposts` - Get repost data

### Required Environment Variables
```typescript
TWITTER_BEARER_TOKEN: string
TWITTER_USER_ID: string
CACHE_TTL: number
MAX_RETRIES: number
RETRY_DELAY: number
```

## Technical Considerations
- Error handling for Twitter API rate limits and downtime
- Efficient caching strategy to minimize API calls
- Logging for monitoring and debugging
- Type safety throughout implementation

## Security
- Validate all requests
- Secure storage of Twitter API credentials
- Rate limiting for DO endpoints

## Testing
- [ ] Unit tests for rate limiting logic
- [ ] Integration tests for Twitter API interaction
- [ ] Cache behavior tests
- [ ] Error handling tests

## Related Documentation
- Twitter API v2 Documentation
- Cloudflare Durable Objects Documentation
- Rate Limiting Best Practices

## Definition of Done
- [ ] Implementation complete with types
- [ ] Tests passing
- [ ] Documentation updated
- [ ] Error handling implemented
- [ ] Logging and monitoring in place
- [ ] PR review completed

**Comment by whoabuddy** [comment]
Closing as stale - can revisit later if needed.
